/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_firstpage;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;
import java.awt.Color;
import java.sql.SQLException;



public class first_page extends JFrame {
    
    private int stock_petrol,stock_d;
    
    private Timer timer;
    private boolean isVisible;
    Connection conn;
    
    public first_page() {
        conn = db.dbconnect();
        initComponents();
        
        stock = new JLabel("LOW FUEL");
        stock.setFont(new Font("Stencil", Font.BOLD, 18));
        stock.setForeground(Color.RED);
        stock.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel3.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 10, 10));
        
        stock_deisel = new JLabel("LOW FUEL");
        stock_deisel.setFont(new Font("Stencil", Font.BOLD, 18));
        stock_deisel.setForeground(Color.RED);
        stock_deisel.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel4.add(stock_deisel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 10, 10));

        
        timer = new Timer(800, (ActionEvent e) -> {
            isVisible = !isVisible;
            stock.setForeground(isVisible ? Color.RED : Color.BLACK);
            stock_deisel.setForeground(isVisible ? Color.RED : Color.BLACK);
        });
        timer.start();
        
        
        try{
            PreparedStatement p = conn.prepareStatement("select stock_up from product_update where type ='petrol'");
            ResultSet rs = p.executeQuery();
            while (rs.next()) {
               stock_petrol = rs.getInt("stock_up");
               }
            if(stock_petrol >= 100)
            {
                stock.setVisible(false);
            }
        }
            catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Order unsucessfull try again"+e);
            System.out.println(e);
            
        }
        try{
            PreparedStatement p = conn.prepareStatement("select stock_up from product_update where type ='deisel'");
            ResultSet rs = p.executeQuery();
            while (rs.next()) {
               stock_d = rs.getInt("stock_up");
               }
            if(stock_d <= 100)
            {
                stock_deisel.setVisible(true);
            }
            else{
                stock_deisel.setVisible(false);
            }
               
        }
            catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Order unsucessfull try again"+e);
            System.out.println(e);
            
        }
    }
    private void stopBlinking() {
    // Stop the timer
    timer.stop();
    // Set the visibility of the label to false
    stock.setVisible(false);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        petrol = new javax.swing.JButton();
        diesel = new javax.swing.JButton();
        adminbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        stock = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        stock_deisel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 140, 81, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(253, 213, 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        petrol.setBackground(new java.awt.Color(0, 0, 0));
        petrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/gasoline (1).png"))); // NOI18N
        petrol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petrolMouseClicked(evt);
            }
        });
        petrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petrolActionPerformed(evt);
            }
        });
        jPanel2.add(petrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 130));

        diesel.setBackground(new java.awt.Color(0, 0, 0));
        diesel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/gasoline.png"))); // NOI18N
        diesel.setText("DIESEL");
        diesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dieselMouseClicked(evt);
            }
        });
        jPanel2.add(diesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 140, 130));

        adminbt.setBackground(new java.awt.Color(0, 0, 0));
        adminbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/administrator.png"))); // NOI18N
        adminbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtActionPerformed(evt);
            }
        });
        jPanel2.add(adminbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 140, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Reliance Petrolium Pvt Limited");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 600, 60));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel2.setText("Thank You For Choosing Us.......");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 450, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setText("Select any options");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 260, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PETROL");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("DIESEL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ADMINISTRATOR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/pump image2.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 300));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/pump image2_1.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/pump image2_1.jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 230, -1));

        jPanel3.setBackground(new java.awt.Color(253, 213, 4));

        stock.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        stock.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(stock);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 170, 30));

        jPanel4.setBackground(new java.awt.Color(253, 213, 4));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 800, 600));
        jPanel1.add(stock_deisel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1470, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void petrolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petrolMouseClicked
        
        String type = "PETROL";
        this.dispose();
        new second_page(type).setVisible(true);
    }//GEN-LAST:event_petrolMouseClicked

    private void petrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petrolActionPerformed
        
    }//GEN-LAST:event_petrolActionPerformed

    private void dieselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dieselMouseClicked
        
        String type = "DEISEL";
        this.dispose();
        new second_page(type).setVisible(true);
    }//GEN-LAST:event_dieselMouseClicked

    private void adminbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtActionPerformed
         this.dispose();
         new Admin_login().setVisible(true);
    }//GEN-LAST:event_adminbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbt;
    private javax.swing.JButton diesel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton petrol;
    private javax.swing.JLabel stock;
    private javax.swing.JLabel stock_deisel;
    // End of variables declaration//GEN-END:variables
}

