/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_firstpage;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JOptionPane;


/**
 *
 * @author SANJAI
 */
public class second_page extends javax.swing.JFrame {

    /**
     * Creates new form second_page
     */ 
    private String type,total;
    Connection conn;
    public second_page(String type) {
        this.type = type;
        conn= db.dbconnect();
        initComponents();
        jLabel1.setText(this.type);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cust_name = new javax.swing.JLabel();
        custname = new javax.swing.JTextField();
        veh_num = new javax.swing.JLabel();
        vehnum = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        ord_rups = new javax.swing.JLabel();
        fuelrs = new javax.swing.JTextField();
        procedbt = new javax.swing.JButton();
        clearbt = new javax.swing.JButton();
        closebt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(253, 213, 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setText("PETROL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 70));

        cust_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cust_name.setText("Customer Name");
        jPanel2.add(cust_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 110, 30));

        custname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(custname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 190, 30));

        veh_num.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        veh_num.setText("Vehicle Number");
        jPanel2.add(veh_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));

        vehnum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(vehnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 190, 30));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light motor Vehicle", "Three Wheleer", "Heavy Motor Vehicle", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 370, -1));

        ord_rups.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ord_rups.setText("Fuel Needed in Liters");
        jPanel2.add(ord_rups, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 160, 20));

        fuelrs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(fuelrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 190, 30));

        procedbt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        procedbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/forward-button.png"))); // NOI18N
        procedbt.setText("PROCEED");
        procedbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procedbtMouseClicked(evt);
            }
        });
        jPanel2.add(procedbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 140, 30));

        clearbt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/roundabout.png"))); // NOI18N
        clearbt.setText("CLEAR");
        clearbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtMouseClicked(evt);
            }
        });
        jPanel2.add(clearbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 120, 30));

        closebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/close (1).png"))); // NOI18N
        closebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtMouseClicked(evt);
            }
        });
        jPanel2.add(closebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/pump image2.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 440, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_firstpage/pump image2_1.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 650, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1407, 736));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void procedbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procedbtMouseClicked
            
        String type = this.type;
        String name = custname.getText();
        String vname = vehnum.getText();
        String vtype =(String)jComboBox1.getSelectedItem();
        String fuel = fuelrs.getText();    
        
        
        String item = null;
        try{
        PreparedStatement pst = conn.prepareStatement("SELECT rate_up from product_update where `type`='"+type+"'");
            
         ResultSet rs = pst.executeQuery();
         while(rs.next()){
            item=rs.getString("rate_up");
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);    
    }
            this.dispose();
            pay_petrol pay = new pay_petrol(name,vname,vtype,fuel,item,type);
            pay.setVisible(true);  

    }//GEN-LAST:event_procedbtMouseClicked

    private void clearbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtMouseClicked
        String myval="default";
        this.dispose();
        new second_page(myval).setVisible(true);
    }//GEN-LAST:event_clearbtMouseClicked

    private void closebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtMouseClicked
        this.dispose();
        new first_page().setVisible(true);
    }//GEN-LAST:event_closebtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String myval="default";
                new second_page(myval).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbt;
    private javax.swing.JButton closebt;
    private javax.swing.JLabel cust_name;
    private javax.swing.JTextField custname;
    private javax.swing.JTextField fuelrs;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel ord_rups;
    private javax.swing.JButton procedbt;
    private javax.swing.JLabel veh_num;
    private javax.swing.JTextField vehnum;
    // End of variables declaration//GEN-END:variables
}
